### ISSUE TITLE
Feedback rd. 2

### ISSUE THREAD

**Issue by mlimberg** [Andrey-1992/Intention-Timer#16]
First off the UI looks and works great! Nice work. super clean. 

One question on it tho, is the timer supposed to delay a second before starting? I guess I expected it to start ticking right away but it looks like it delays. Just wanted to call it out. 

### Some other random feedback:

* Since you already made a var for `activeButton` I'd consider adding one for checking all of the input values:
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/main.js#L98

Something like:
```js
var isFormComplete = descriptionInput.value && minuteInput.value && secondInput.value
```

<br />

---

<br />

* With this block of code...
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/main.js#L142-L148

Instead of checking the category with an `if` statement, what about being more explicit and using the `category` as part of the classname? Think interpolation. Could chop it down to 1-2 lines of code. 

<br />

---

<br />

It looks like these operations are pretty similar, perhaps a func get the value based on a `seconds` argument? Not necessarily any less code in this small use-case but if you think about an app growing you'd want helpers to avoid re-writing this logic over and over and over. Plus it's good practice :) 
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/main.js#L141
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/main.js#L155

<br />

---

<br />

On this line:
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/main.js#L161
Does it make more sense for mins to do a loose equality comparison? Meaning if for any reason `minutes` was `0` or `"0"` would you still want that to evaluate to true in either case? 

<br />

---

<br />

In regards to spacing - don't be afraid to add spaces or indents for readability and try to stay consistent with patterns. Totally just a recommendation but it helps you absorb chunks of code faster and is especially helpful as you're learning. Some examples:

* In `activity.js` add a blank line before each method
* Perhaps indent the strings of html to indent like html normally would:
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/main.js#L182-L193
* In `checkInput` you have some great spacing:
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/main.js#L92-L103
Then in `createActivity` it's all jammed together:
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/main.js#L120-L135

My own personal preference is to space out `if` blocks and return statements. An example might be:

```js
function someFunc() {
  var thingOne = 'stuff'
  var thingTwo = doOtherStuff()
  
  if (thingTwo) {
    // logic here
  }
  
  return something here
}
```

<br />

---

<br />

This can just be: `padding: 30px 100px`
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/styles.css#L59

<br />

---

<br />

I don't think this is doing what you want it to. It makes the content have scroll below the fold, even if it's not needed (i.e. 
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/styles.css#L64
<br />
Additionally if I have a bunch of past activities (12+) it starts to position the `main-view` down (see below)

![image](https://user-images.githubusercontent.com/16227556/115345888-add6af80-a16c-11eb-807e-7d0c11004580.png)

<br />

---

<br />

I think you meant for this class to be on the button element? 
https://github.com/Andrey-1992/Intention-Timer/blob/f8034912a45a835a2964430fd35b349d20493c34/index.html#L44

If not you at least don't need the `cursor: pointer` on the class because A) you already set it on all `button` elements in the css on line 138 and B) it doing it here has the cursor as a pointer in the entire div, not just over the button. 

<br />

---

<br />

Ok - that's a lot. Just do what you can and learn from the rest! Holler with any questions or push-back. Happy to discuss anything that's confusing or you're not sure you agree with.

**Comment by janitastic** [comment]
Thank you for all the value feedback! We made most of your changes, and learned a lot of new tricks.
