### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by mlimberg** [Andrey-1992/Intention-Timer#9]
I would consider making this a var like `validate` for easier readability
https://github.com/Andrey-1992/Intention-Timer/blob/746b1258b0c1afadb0bd4e4e2c902a35fc4aed25/main.js#L91

Should seconds be a string just like minutes? 
https://github.com/Andrey-1992/Intention-Timer/blob/746b1258b0c1afadb0bd4e4e2c902a35fc4aed25/main.js#L142

It looks like you're running into issues comparing and computing numbers with strings. I would consider building ways to streamline the data you're using. When you pull the value from the inputs, it's a string. But that doesn't mean you can't change and store the value as a number when dealing w/ comparisons and operations... and then reformatting back to a string before rendering on the page. 

hint: if minutes is "3" and seconds is "2", what do you get when you run the logic from line 119? 

```js
totalSeconds = (minuteInput.value * 60) + secondInput.value;
```

**Comment by janitastic** [comment]
Thank you Mike! This was our solve! We'll make this update shortly.
